### PR TITLE
Fix task list with states and authors

### PR DESCRIPTION
**Pull request by YCChenVictor**
先創個訂單，因為藍新要用

然後讓 view 好看一點

### CODE REVIEW

**Review by huihsinhsiao — APPROVED** [review]
👍

**Review by yuRicky09 — APPROVED** [review]
ok thank

**Review by nauosika — APPROVED** [review]
ok

**Review by Wei-Lun-Cheng — APPROVED** [review]
👍

**Review by Wei-Lun-Cheng — COMMENTED** [review]
👍
大家加油！

**Pull request merged**
